env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - airbnb-base
  - react-app
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: 
  import/extensions: 0
  no-console: 0
  react/prop-types": "off"
  import/no-anonymous-default-export: "off"
  react/jsx-indent: 'error'

