env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  import/extensions: 0
  no-console: 0
  import/no-unresolved: 0
  no-param-reassign: 0
  react/prop-types: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/function-component-definition: 0
