env:
  browser: true
  es2021: true
extends:
  - airbnb
  - plugin:react/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  import/extensions: "off"
  no-console: 0
  import/no-unresolved: "off"
  import/no-duplicates: "off"
  no-param-reassign: "off"
  react/prop-types: "off"
  import/no-anonymous-default-export: "off"
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/function-component-definition: 0
